"""
Image-right layout — text on the left, image floated to the right.
Auto-selected when a markdown image follows the slide's text content.
"""
import re

_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
_IMAGE_RE = re.compile(r"!\[.*?\]\(.*?\)")


def match(slide) -> bool:
    clean = _COMMENT_RE.sub("", slide.content)
    images = _IMAGE_RE.findall(clean)
    if len(images) != 1:
        return False
    img_match = _IMAGE_RE.search(clean)
    before = clean[: img_match.start()].strip()
    after = clean[img_match.end() :].strip()
    return bool(before) and not after

# Used to remove wrapping <p> tags from the image HTML generated by markdown
_P_WRAP_RE = re.compile(r"^<p>(.*)</p>$", re.DOTALL)


def html(slide, md) -> str:
    img_match = _IMAGE_RE.search(slide.content)
    if img_match:
        img_html = md(img_match.group(0)).strip()
        img = _P_WRAP_RE.sub(r"\1", img_html)
        text_body = md(slide.content.replace(img_match.group(0), "").strip())
        return (
            '<div class="slide-layout image-right">'
            f'<div class="image-text">{text_body}</div>'
            f'<div class="img-container">{img}</div>'
            "</div>"
        )
